apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    app.kubernetes.io/name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: django
          image: docker.io/nekto007/django_app:nekto007
          imagePullPolicy: Never
          command: ["python", "./manage.py", "migrate", "--no-input"]
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secrets
      restartPolicy: OnFailure