apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app.kubernetes.io/name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-deployment
    spec:
      containers:
        - name: container-django
          image: docker.io/nekto007/django_app:nekto008
          ports:
            - containerPort: 80
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: DATABASE_URL
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: SECRET_KEY
          envFrom:
            - configMapRef:
                name: django-config