apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django-app
data:
  DATABASE_URL: "postgres://username:password@hostname:port/dbname"
  SECRET_KEY: "your_secret_key"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
