apiVersion : v1
kind: Pod
metadata:
  name: django-app
  labels:
   app.kubernetes.io/name: django-app
   app.kubernetes.io/instance: django-app-mini
spec:
 containers:
  - name : container-django
    image: django_app
    ports:
     - containerPort: 80
    env:
    - name: SECRET_KEY
      value: "REPLACE_ME"
    - name: DEBUG
      value: "TRUE"
    - name: ALLOWED_HOSTS
      value: "*"
    - name: DATABASE_URL
      value: "postgres://test_k8s:OwOtBep9Frut@192.168.1.212:5432/test_k8s"

---

apiVersion : v1
kind: Service
metadata:
  name: django-service
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: django-app-mini
spec:
  selector:
    app.kubernetes.io/name: django-app
  ports:
    - name: traffic-service
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
