apiVersion : apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
   app.kubernetes.io/name: django-app
   app.kubernetes.io/instance: django-app-mini
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django-app
      app.kubernetes.io/component: django-app-mini
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-app
        app.kubernetes.io/component: django-app-mini
    spec:
      containers:
      - name : container-django
        image: django_app:nekto007
        ports:
         - containerPort: 80
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: DEBUG
          value: "TRUE"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DATABASE_URL

---

apiVersion : v1
kind: Service
metadata:
  name: django-service
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: django-app-mini
spec:
  selector:
    app.kubernetes.io/name: django-app
  ports:
    - name: traffic-service
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
